import type { Metadata } from "next";
import './styles/Homepage.module.css';
import './styles/globals.css';
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="body-container">
        <Sidebar />
        <div className="main-container">
          <Header />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
