import { Metadata } from "next";
import { Poppins } from "next/font/google";
import LayoutWrapper from "./layoutWrapper"; // Client wrapper
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Shine Masters Operations Hub",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className={`${poppins.variable}`}>
      <body>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
